language: node_js
node_js:
  - node

before_install:
  - set -e
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn install

before_script:
  - greenkeeper-lockfile-update

script:
  - yarn run test

after_script:
  - greenkeeper-lockfile-upload
  - echo "BUILD FINISHED"
